<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>q</string>
	</array>
	<key>name</key>
	<string>q</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/
</string>
			<key>comment</key>
			<string>string</string>
			<key>end</key>
			<string>\\
</string>
			<key>name</key>
			<string>comment.block.source.q</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string</string>
			<key>match</key>
			<string>^/.+</string>
			<key>name</key>
			<string>comment.block.source.q</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^/[ ]*$</string>
			<key>comment</key>
			<string>string</string>
			<key>end</key>
			<string>^\[ ]*$</string>
			<key>name</key>
			<string>comment.block.documentation</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string</string>
			<key>match</key>
			<string>^/.+</string>
			<key>name</key>
			<string>comment.block.source.q</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string</string>
			<key>match</key>
			<string> /.*</string>
			<key>name</key>
			<string>comment.line.source.q</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\\
</string>
			<key>comment</key>
			<string>string</string>
			<key>end</key>
			<string>\\
</string>
			<key>name</key>
			<string>comment.block.source.q</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string</string>
			<key>match</key>
			<string>/ .*</string>
			<key>name</key>
			<string>comment.line.source.q</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string</string>
			<key>match</key>
			<string>".*?"</string>
			<key>name</key>
			<string>string.quoted.string.source.q</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string</string>
			<key>match</key>
			<string>`[:/a-zA-Z0-9_.]+</string>
			<key>name</key>
			<string>string.interpolated.symbol.source.q</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.complex.source.q</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>variable definition</string>
			<key>match</key>
			<string>(?=([^a-zA-Z0-9]|\b))([a-zA-Z]+[a-zA-Z0-9_\.]*):</string>
			<key>name</key>
			<string>other.source.q</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.complex.source.q</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>variable definition</string>
			<key>match</key>
			<string>(?=([^a-zA-Z0-9]|\b))([a-zA-Z]+[a-zA-Z0-9_\.]*)[+-,]:</string>
			<key>name</key>
			<string>other.source.q</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.complex.source.q</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>q keyword</string>
			<key>match</key>
			<string>(?=(\W|\b))(abs|acos|aj|aj0|all|and|any|asc|asin|asof|atan|attr|avg|avgs|bin|binr|by|ceiling|cols|cor|cos|count|cov|cross|csv|cut|delete|deltas|desc|dev|differ|distinct|div|do|dsave|each|ej|ema|enlist|eval|except|exec|exit|exp|fby|fills|first|fkeys|flip|floor|from|get|getenv|group|gtime|hclose|hcount|hdel|hopen|hsym|iasc|idesc|if|ij|ijf|in|insert|inter|inv|key|keys|last|like|lj|ljf|load|log|lower|lsq|ltime|ltrim|mavg|max|maxs|mcount|md5|mdev|med|meta|min|mins|mmax|mmin|mmu|mod|msum|neg|next|not|null|or|over|parse|peach|pj|prd|prds|prev|prior|rand|rank|ratios|raze|read0|read1|reciprocal|reval|reverse|rload|rotate|rsave|rtrim|save|scan|scov|sdev|select|set|setenv|show|signum|sin|sqrt|ss|ssr|string|sublist|sum|sums|sv|svar|system|tables|tan|til|trim|type|uj|ujf|ungroup|union|update|upper|upsert|value|var|view|views|vs|wavg|where|while|within|wj|wj1|wsum|ww|xasc|xbar|xcol|xcols|xdesc|xexp|xgroup|xkey|xlog|xprev|xrank)(?=(\W|\b))</string>
			<key>name</key>
			<string>other.source.q</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.complex.source.q</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>datetime</string>
			<key>match</key>
			<string>(?=(\W|\b))([0-9]{4}\.[0-9]{2}\.[0-9]{2}[TD]?[0-9]{2}:[0-9]{2}:[0-9]{2}(:[0-9]{2})?(\.[0-9]{3,6})?)(?=(\W|\b))</string>
			<key>name</key>
			<string>other.source.q</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.complex.source.q</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>time</string>
			<key>match</key>
			<string>(?=(\W|\b))([0-9]{4}\.[0-9]{2}\.[0-9]{2}[TD]?)(?=(\W|\b))</string>
			<key>name</key>
			<string>other.source.q</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.complex.source.q</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>date</string>
			<key>match</key>
			<string>(?=(\W|\b))([0-9]{2}:[0-9]{2}:[0-9]{2}(:[0-9]{2})?(\.[0-9]{3,6})?)(?=(\W|\b))</string>
			<key>name</key>
			<string>other.source.q</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.complex.source.q</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>boolean,short,integer,long</string>
			<key>match</key>
			<string>(?=(\W|\b))([-]?[0-9]+[bhijef]{0,1}(\.[0-9]+[m]?)?|0x[a-f0-9]+)(?=(\W|\b))</string>
			<key>name</key>
			<string>other.source.q</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.q</string>
	<key>uuid</key>
	<string>f815231e-15c5-543f-985a-744aa1154ded</string>
</dict>
</plist>
